### PR TITLE
package this project

### PR DESCRIPTION
**Pull request by bung87**

### CODE REVIEW

**Comment by nzw0301** [comment]
Thank you for your PR! I want to use `README.org`. Please remain it.

I have a question about your PR:  Why do you remove it?
I like type hint.

**Comment by bung87** [comment]
I'm not familiar with the .org format ,since I cant find a IDE extension to highlight the format to give me clue how to add code block,I've make some PRs to some projects ,many of them seems to be not maintained,so if I need to use it in the future or may help someone,it must be well documented.

If you willing to merge this pr,you may check setup.py fill some information,and change the Installation git repo address on document.

**Comment by nzw0301** [comment]
Sorry for my ambiguous comment. Why do you remove type hint?
Currently, I want to merge this PR excluding removing type hint and changing file format of README.

**Comment by bung87** [comment]
Sorry, I just know it 's new feature in py3.5,If I knew I would not remove it simply,but without it make project more compatible,if you just decide to only support 3.5 above you may specify the version in setup.py at `install_requires` and `classifiers`

**Comment by nzw0301** [comment]
I agree with you. But, I only support python >= 3.5 because this repo is not a practical implemented code. 

Yes, I will add it to README or `setup.py`.

**Comment by bung87** [comment]
since that you may copy what you need inside this PR,leave my fork version to  be compatible version.

**Comment by nzw0301** [comment]
OK, thank you!

**Pull request closed without merging**
